config/routes.rb
Rails.application.routes.draw do
  # root to: 'landing_page#index'
  # get 'landing_page/index'
  devise_for :users
  resources :users
  root to: 'products#index'
  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :cost, presence: true
  validates :country_of_origin, presence: true
   # validates_length_of :content_body, maximum: 250
   # validates_length_of :content_body, minimum: 50

  # scope for most reviewd product
  scope :most_reviewed, -> {(
    select("products.id, products.name, products.country_of_origin, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(1)
    )}
  # scope for three recent products
  scope :three_recent_products, -> { order(created_at: :desc).limit(3)}
  # scope for country_of_origin query
  scope :local_product, -> { ( where(country_of_origin: "United States").limit(5)) }

  before_save(:titleize_product)

  private
    def titleize_product
      self.name = self.name.titleize
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
  validates :author, presence: true
  validates :rating, presence: true
  validates :content_body, presence: true
  validates :product_id, presence: true
  validates_length_of :content_body, minimum: 50
  validates_length_of :content_body, maximum: 250
  validates_inclusion_of :rating, in: 1..5
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true
  has_many :reviews, dependent: :destroy
  # has_many :products, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @products = Product.all
    @recent_products = Product.three_recent_products
    @most_reviewed_products = Product.most_reviewed
    @local_products = Product.local_product
    render :index
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully added!"
      redirect_to products_path
    else
      flash[:alert] = "Could not save new product!"
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def show
    @product = Product.find(params[:id])
    render :show
  end

  def update
    @product= Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product successfully updated!"
      redirect_to products_path
    else
      flash[:alert] = "Could not update this product!"
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product successfully deleted!"
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :cost, :country_of_origin)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, :except => [:index]

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review successfully added!"
      redirect_to product_path(@product)
    else
      flash[:alert] = "Could not save new review!"
      render :new
    end
  end

  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to product_path(@review.product)
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@review.product)
  end
  # Other controller actions go here.

  private
  def review_params
    params.require(:review).permit(:author, :content_body, :rating)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

  def index
    @users = User.all
    render :index
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
    render :edit
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def update
    @user= User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductReview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <%= current_user.email %> | <%= link_to "Sign out", '/users/sign_out', method: :delete %>
      <% else %>
      <%= link_to "Sign up", '/users/sign_up' %> | <%= link_to "Sign in", '/users/sign_in' %>
    <% end %>

    <%= flash[:alert] %>
    <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= form_for @product do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :cost %>
<%= f.number_field :cost %>
<%= f.label :country_of_origin %>
<%= f.text_field :country_of_origin %>
<%= f.submit  %>
<% end %>

app/views/products/index.html.erb
<h1>The Recent Three Products</h1>

<% if @recent_products.any? %>
  <ul>
    <% @recent_products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no recent products yet.</p>
<% end %>

<h1>The Most Reviewed Products</h1>

<% if @most_reviewed_products.any? %>
  <ul>
    <% @most_reviewed_products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no most reviewed products yet.</p>
<% end %>

<p><%= link_to "Create new product", new_product_path %></p>

<h1>The Local Products from United States</h1>

<% if @local_products.any? %>
  <ul>
    <% @local_products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no local products yet from United States.</p>
<% end %>

<p><%= link_to "Create new product", new_product_path %></p>

<h1>All Products Information</h1>

<% if @products.any? %>
  <ul>
    <% @products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no products yet.</p>
<% end %>

<p><%= link_to "Create new product", new_product_path %></p>

app/views/products/new.html.erb
<h1>New product</h1>

<% if @product.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @product.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cost %>
  <%= f.number_field :cost %>
  <%= f.label :country_of_origin %>
  <%= f.text_field :country_of_origin %>
  <%= f.submit  %>
<% end %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h3><%= @product.cost %></h3>
<h3><%= @product.country_of_origin %></h3>

<% if @product.reviews.any? %>
  <h4>Here are the reviews for this product:</h4>

  <% @product.reviews.each do |review| %>
    <ul>
      <li>
        <%= link_to review.author, product_review_path(@product, review) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No reviews are listed for this product.</p>
<% end %>

<p><%= link_to "Add a review", new_product_review_path(@product) %></p>

<p><%= link_to "Edit", edit_product_path(@product) %></p>
<p><%= link_to "Delete product", product_path(@product),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to products", products_path %></p>

app/views/reviews/edit.html.erb
<h1>Edit Review:</h1>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_area :content_body %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <p><%= f.submit %></p>
<% end %>

app/views/reviews/new.html.erb
<h1>Add a new review:</h1>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_area :content_body %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <p><%= f.submit %></p>
<% end %>

app/views/reviews/show.html.erb
<h1>Review: <%= @review.author %></h1>
<h2>Product: <%= @product.name %></h2>
<h3><%= @review.content_body %></h3>
<h3><%= @review.rating %></h3>

<p><%= link_to "Edit review", edit_product_review_path(@product, @review) %></p>
<p><%= link_to "Delete review", product_review_path(@product, @review),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to product", product_path(@product) %></p>

app/views/users/edit.html.erb
<h1>Edit user </h1>

<%= form_for @user do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.submit  %>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<% if @users.any? %>
  <ul>
    <% @users.each do |user| %>
    <li> <%= link_to user.email, user_path(user) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no users yet.</p>
<% end %>


<p><%= link_to "Create new user", new_user_path %></p>

app/views/users/new.html.erb
<h1>New user</h1>

<% if @user.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.submit  %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>

<% if @user.products.any? %>
  <h4>Here are the products for this user:</h4>

  <% @user.products.each do |product| %>
    <ul>
      <li>
        <%= link_to product.title, user_product_path(@user, product) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No products are listed for this user.</p>
<% end %>

<p><%= link_to "Add a product", new_user_product_path(@user) %></p>

<p><%= link_to "Edit", edit_user_path(@user) %></p>
<p><%= link_to "Delete", user_path(@user),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

<p><%= link_to "Return to users", users_path %></p>